### ISSUE TITLE
Every thing working Done. But How to load DOM/Javascript Functions with content?

### ISSUE THREAD

**Issue by khansab4** [pklauzinski/jscroll#102]
Javascript Functions is not working in pagination's Loaded Content.???

**Comment by stoney024** [comment]
It seems not. I can't get any script to work on loaded content.

**Comment by htmgarcia** [comment]
@stoney024 I had the same problem and the solution was to duplicate the event that isn't working in loaded content inside the callback option key.

**Comment by pklauzinski** [comment]
@khansab4 @stoney024 you must initialize any javascript behaviors on new content that is introduced to the page, either by using the `callback` option, as @htmgarcia suggests, or you can _delegate_ your behaviors from a parent selector that does not get removed from the DOM during a session.

For example:

```
$('main').on('click', '.jscroll > .new-content a', function(e) {
    e.preventDefault();
    // Do something here
});
```

If you initialize your behaviors in this way, they will always work, even for new content that is loaded from jScroll.

For more information, see jQuery's documentation for `.on()`, specifically the section on "direct and delegated events."

http://api.jquery.com/on/#direct-and-delegated-events
