### ISSUE TITLE
Use of contentSelector parameter causes loaded scripts to not be executed.

### ISSUE THREAD

**Issue by neobonzi** [pklauzinski/jscroll#121]
When using the "contentSelector" parameter, jQuery's "load()" method is used with a suffixed selector expression which causes script tags to be stripped prior to dom being updated. This causes all loaded scripts to not be executed.

See "Script Execution" under http://api.jquery.com/load/

**Comment by pklauzinski** [comment]
Executing scripts within the loaded HTML does not fall within the scope of jScroll. If you need to execute javascript upon loading the next page, use the `callback` option.
