### ISSUE TITLE
nextSelector not found

### ISSUE THREAD

**Issue by abhayin** [pklauzinski/jscroll#122]
Loading the function after second pagination it throw this error
**jScroll: nextSelector not found - destroying**
please help me out with this.....

**Comment by pklauzinski** [comment]
@abhayin this is expected when there is no `nextSelector` present in a response. This means that jScroll has reached the end of its pagination. If you are expecting a paged result here, make sure that your `nextSelector` option is set correctly and that the selector is, in fact, being returned in your AJAX response.
