### ISSUE TITLE
Removing content from main div prevent jScroll from triggering (no scroll)

### ISSUE THREAD

**Issue by bigretromike** [pklauzinski/jscroll#137]
I have page that list `div` objects (containing text,pic,buttons) in list way. when I scroll down jScroll trigger and populate list with more content - but when I remove those `div`s with clicking each button on them the jscroll dosn't trigger because i don't scroll page. 

I wanted to exposed `_load()` but it would trigger each time I click button so it would load to many pages ahead which is bad idea.

Is there a way to trigger jscroll somehow other than scroll down (at the end there is no scroll bar because main `div` have non or one `div` with content)

**Comment by pklauzinski** [comment]
Yes, you can set the `autoTrigger` option to `false` which will instead use the `nextSelector` link's `click` event to trigger the loading of the next set of content.

See Example 2 on [jscroll.com](http://jscroll.com/) for a demo of this.

**Comment by bigretromike** [comment]
That dont resolve my issue, i would like to stick with autotrigget=true. I would have to detect page height and then manipulat autotrigger to off but would that evem work?
