### ISSUE TITLE
Request:: A javascript function to load after the html has been rendered?

### ISSUE THREAD

**Issue by m-maharjan** [pklauzinski/jscroll#156]
Just like loadingFunction, which is called before the xhr request, I need a function that needs to be called after the request has been completed and the view has been apended. Is there any option that I can use?

**Comment by pklauzinski** [comment]
Hi @m-maharjan,

Yes, you can use the `callback` option to do just that!

Documentation here:
https://jscroll.com/#/configuration?id=callback

**Comment by m-maharjan** [comment]
Thank you so much it worked, I thought it was called when there is no data set to be loaded at the end.
