### ISSUE TITLE
Support sending URL params.

### ISSUE THREAD

**Issue by Leodau** [pklauzinski/jscroll#170]
This is an enhancement request,

JSCROLL should absolutely support **url query options**, let's say you need to send filters to your backend to get different result.

'?customParams=data'
🙃🙃

**Comment by piterjov** [comment]
Any update on this

**Comment by eqxDev** [comment]
You can do this with the callback function and window history.
```           
var url = new URL(window.location.href);
var page = url.searchParams.get("page");
if (page == null) {
   page = 1;
}
page = parseInt(page) + 1;
url.searchParams.set("page", page);
var newUrl = url.href;
history.pushState(null, null, newUrl);```
