### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by TNDJX** [pklauzinski/jscroll#171]
Hi i am using your plugin, but i can't make it work on mobile devices my issue is the same like this post on Stack:
[https://stackoverflow.com/questions/45035411/jscroll-not-working-on-android-device](url)

Is there a way to to use jscroll on mobile devices?

**Comment by pklauzinski** [comment]
Try setting the `padding` option to something above 0, maybe 20 or so, so that the auto-scroll is triggered before the very end of the page.

```js
$('.jscroll').jscroll({
    loadingHtml: '<img src="loading.gif" alt="Loading" /> Loading...',
    padding: 20,
    nextSelector: 'a.jscroll-next:last',
    contentSelector: 'li'
});
```

Full options list here:
https://github.com/pklauzinski/jscroll#options

**Comment by gojimmypi** [comment]
@pklauzinski that `padding: 20` is certainly a big help, however in my situation the scroll gives up on page 12 of 15. It simply won't go any further on a mobile device. I tried increasing to 60, but the next page just does not trigger. It works fine on the desktop.

Here's my init:

```
$(document).ready(function () {
	$('.articles').jscroll({
		contentSelector: 'article, .pagination',
		nextSelector: '.next',
		padding: 60,
		callback: removeWrap,
	});
});

```
Here's a snip of my article elements, loaded 8 at a time on 10 pages beyond the initial display before giving up on the [last one](https://gojimmypi.github.io/gridster-jekyll-theme/stm32-smart-v2-to-st7735-tft-lcd/) and does not load the [next set on page 12](https://gojimmypi.github.io/gridster-jekyll-theme/page/12/):
![image](https://user-images.githubusercontent.com/13059545/118574708-d638d600-b739-11eb-8f71-3112493409fa.png)

Similar to operations prior to the `padding: 20` setting, the event is not triggered.

I later tried `padding: 120` and curiously it gave up _sooner_, getting stuck on page 5. 

Ultimately `padding: 10` is what worked best to load all the pages, but I'm left wondering if perhaps this is a device-specific hack? 

Can you provide any more insight on perhaps assigning a fudge value based on the device? 

Perhaps this is related to my bottom border:

![image](https://user-images.githubusercontent.com/13059545/118576100-b5be4b00-b73c-11eb-8a35-7c8dd82f1a7a.png)

The not-hiding-of-pagination on this last page appears to be a side effect of the padding fudge.
