### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by Soullivaneuh** [pklauzinski/jscroll#18]
It would be great if you can integrate a bower.json file for bower manager.

More informations here: http://bower.io/

Thanks.

**Comment by pklauzinski** [comment]
@wodka `jquery.scroll.json` is for the jQuery Plugin Registry, not for bower. This issue will be handled in #24.

**Comment by pklauzinski** [comment]
@Soullivaneuh, @wodka - #24 is now resolved with `bower.json` added in the latest updates, among a few other changes.

**Comment by wodka** [comment]
thx!

**Comment by Soullivaneuh** [comment]
:+1:
