### ISSUE TITLE
Callback only loaded the first time

### ISSUE THREAD

**Issue by juju95** [pklauzinski/jscroll#25]
Hi,

Made this script works for my need but just have a bugg

callback function is only loaded at 1st page loading, when jscroll get page 2 content etc, callback is never called again

for my test just simply used : 

```
 function CallTest()
         {
             alert("Call function called");
         }

    $('#ListePhotos').jscroll({
        debug : true,
        loadingHtml: '<img src="loading.gif" alt="Loading" /> Loading...',
        padding: 20,
        pagingSelector : "#Pagination",
        nextSelector: 'a#NextLink:last',
        contentSelector : "#ListePhotos",
        callback : CallTest(),

    });
```

**Comment by khansab4** [comment]
how to callback function when function name & id & class with row id from table ???



<div class="scroller">
    <div class="scrpller">
    
        @foreach($timeline as $img)

        <img src="{{$img->link}}" style="width:500px;">
        <br><br>
        <p id="p{{$img->id}}" style="background-color:green;  padding:10px;">{{$img->id}}</p>
        <br>
        <button id="hide{{$img->id}}">Hide</button>
        <button id="show{{$img->id}}">Show</button>
        <hr>

        <script type="text/javascript">
function myfunc(){ 

        $("#hide{{$img->id}}").click(function(){
            $("#p{{$img->id}}").hide();
        });
        $("#show{{$img->id}}").click(function(){
            $("#p{{$img->id}}").show();
        });

        
            document.getElementById('p{{$img->id}}').innerHTML="Hello world";
        }
        </script>
        @endforeach

    {{$timeline->links()}}
    </div>
    
    
</div>

<script>

  jQuery(document).ready(function($){
 
        //hides the default paginator
        $('ul.pagination:visible:first').hide();
 
        //init jscroll and tell it a few key configuration details
        //nextSelector - this will look for the automatically created 
        //contentSelector - this is the element wrapper which is cloned and appended with new paginated data
        $('.scroller').jscroll({
            debug: true,
            autoTrigger: true,
            nextSelector: '.pagination li.active + li a',
            contentSelector: '.scroller',
            callback:
            myfunc,
             function() {
                
                //again hide the paginator from view
                $('ul.pagination:visible:first').hide();
 
            }
        });
    });
</script>

**Comment by khansab4** [comment]
how to callbacl function when function name, class, & id with row primary id from table ???

`'
<div `class="scroller">`
    <div class="scrpller">
    
        @foreach($timeline as $img)

        <img sr//c="{{$img->link}}" style="width:500px;">
        <br><br>
        <p id="p{{$img->id}}" style="background-color:green;  padding:10px;">{{$img->id}}</p>
        <br>
        <button id="hide{{$img->id}}">Hide</button>
        <button id="show{{$img->id}}">Show</button>
        <hr>

        <script type="text/javascript">
function myfunc(){
        $("#hide{{$img->id}}").click(function(){
            $("#p{{$img->id}}").hide();
        });
        $("#show{{$img->id}}").click(function(){
            $("#p{{$img->id}}").show();
        });

        
            document.getElementById('p{{$img->id}}').innerHTML="Hello world";
        }
        </script>
        @endforeach

    {{$timeline->links()}}
    </div>
    
    
</div>

<script>

  jQuery(document).ready(function($){
 
        //hides the default paginator
        $('ul.pagination:visible:first').hide();
 
        //init jscroll and tell it a few key configuration details
        //nextSelector - this will look for the automatically created 
        //contentSelector - this is the element wrapper which is cloned and appended with new paginated data
        $('.scroller').jscroll({
            debug: true,
            autoTrigger: true,
            nextSelector: '.pagination li.active + li a',
            contentSelector: '.scroller',
            callback:
            myfunc,
             function() {
                
                //again hide the paginator from view
                $('ul.pagination:visible:first').hide();
 
            }
        });
    });
</script>
