### ISSUE TITLE
Unable to reinitialize after ajax

### ISSUE THREAD

**Issue by versello** [pklauzinski/jscroll#27]
Having an issue where jscroll doesn't bind after ajax load. I've read "Problem with dynamic content #11" which sounds like my issues, but cannot find a resolution. jscroll doesn't seem to want to find after being destroyed.

	$('#search').on('input propertychange', function() {
		$.ajax({
			url: 'list.php?query=' + $('#search').val(),
			success: function(data){
				$('#file-container').jscroll.destroy();
				$('#file-container').html(data);
				$('#file-container').jscroll({
					debug: true,
					nextSelector: '.more',
					autoTrigger: false,
					loadingHtml: '<div id="processing"></div>'
				});
			}
		});
	});

**Comment by efriandika** [comment]
i have same problem with you.
i just add:

    $('#list-album').removeData('jscroll');

it solved my problem.
