### ISSUE TITLE
Jquery overlapping content for first time!

### ISSUE THREAD

**Issue by evivz** [pklauzinski/jscroll#33]
Hi this is the result page : http://projects.vivek.be/ebaysearch/indexc.php?search=mobile I am using jscroll to load more content. But for the first time content is overlapped over old content! How to solve this?

thansk.

**Comment by pklauzinski** [comment]
Not sure I understand, from looking at the page. This sounds like a CSS issue though, and not an issue with jScroll directly. If you can better define your problem, then please do so and re-open the ticket. Thanks!
