### ISSUE TITLE
Codeigniter & jScroll

### ISSUE THREAD

**Issue by erswelljustin** [pklauzinski/jscroll#37]
Hi

Firstly thanks for this awesome little plugin it has been super easy to get in and running, however I have hit a little bump which I hope you will be able to help with.

On the first load of the view CI places a next link in this case (http://localhost/index.php/board/morePosts/30) and the first scroll works unfortunately jScroll then destroy's the link and it stops.

What I need is a way of loading in a new link for scroll to grab a hold of, should I be using page numbers? I am struggling to work this out as the pagination links are being loaded using PHP and driven to the browser only on first load.

Thanks

Justin

**Comment by pklauzinski** [comment]
I'm not sure about CI specifically, but with each scroll request that you load, you will want to load a link for the next page in your `nextSelector` or else jScroll will self-destroy. That link should come from your server-side script, so how that is loaded is up to you/CI.
