### ISSUE TITLE
return from history

### ISSUE THREAD

**Issue by mamfernandes01** [pklauzinski/jscroll#46]
When a user returns from history. He will begin on top again and needs to scoll again the whole list.

**Comment by pklauzinski** [comment]
jScroll does not interface with the browser History object at this time, nor does it have any type of cache built in. If you go back to a page with a jScroll instance, it will load initially just as any other javascript in the page. I would suggest caching your server side requests if you wish for them to remain once accessed.

Future versions of jScroll will employ caching in some manner. TBD.
