### ISSUE TITLE
Feature Request: Allow for autoTrigger:false after users clicks Next Page

### ISSUE THREAD

**Issue by justinbhayes** [pklauzinski/jscroll#47]
Is there a way to allow all remaining content to load after a user clicks the Next Page button when using the autoTriggerUntil option? For example: A page has 50 results, but I choose to show the first 18 on page load using the autoTriggerUntil option, then I click the Next Page button and the remaining 32 results load (with no additional clicks on any Next Page buttons). The Next Page button would only ever appear once on a page.

**Comment by Arkadis** [comment]
+1

**Comment by pklauzinski** [comment]
This type of functionality would be better served by parameters passed to your server side call in your `nextHref` value. Your initial call would load 18 results, and the URL for your "Next Page button" (`nextHref`) would be something like `/url.json?start=19&end=50`.

IMO, the amount of data returned for each scroll instance should be controlled by your server side (or static) script, and not by jScroll itself.
