### ISSUE TITLE
No next href present but it hit load function

### ISSUE THREAD

**Issue by sumanta-ghosh** [pklauzinski/jscroll#55]
When I don't have any content to load still it hit load. In my page there is no next link.
So I change some _setBindings() and added bellow two lines

```javascript 
if (!$next.length)//if there is no next selector then don't need to bind scroll
   return false;
```
```javascript 
_setBindings = function() {
            var $next = $e.find(_options.nextSelector).first();
            if (!$next.length)
                return false;
            if (_options.autoTrigger && (_options.autoTriggerUntil === false || _options.autoTriggerUntil > 0)) {
                _nextWrap($next);
                if (_$body.height() <= _$window.height()) {
                    _observe();
                }
                _$scroll.unbind('.jscroll').bind('scroll.jscroll', function() {
                    return _observe();
                });
                if (_options.autoTriggerUntil > 0) {
                    _options.autoTriggerUntil--;
                }
            } else {
                _$scroll.unbind('.jscroll');
                $next.bind('click.jscroll', function() {
                    _nextWrap($next);
                    _load();
                    return false;
                });
            }
        },
```

I want to know is't correct or there is another way to do that or it has that type of functionality I implement it incorrectly that's why it hit load function thought there is no next page

**Comment by pklauzinski** [comment]
@sumanta-ghosh - `_setBindings` should never get called unless the nextHref is present within the jscroll element, as referenced in the `_checkNextHref` method:

```javascript
            // Check if the href for the next set of content has been set
            _checkNextHref = function(data) {
                data = data || $e.data('jscroll');
                if (!data || !data.nextHref) {
                    _debug('warn', 'jScroll: nextSelector not found - destroying');
                    _destroy();
                    return false;
                } else {
                    _setBindings();
                    return true;
                }
            }
```

Somehow it is still finding it. Do you have an example of your code?

**Comment by sumanta-ghosh** [comment]
```javascript
$('#artist_list').jscroll({
            autoTrigger: true,
            nextSelector: '.pagination li.active + li a',
            callback: function() {
                if ($(".artist_listing_pagination").length > 1) {
                    $(".artist_listing_pagination:not(:last)").remove();
                }
                init_rating();
            }
        });
```
at the Initialization time _checkNextHref() is not call. _checkNextHref() is calling from _load()
_checkNextHref() function is call from _load() function only

**Comment by yairpe** [comment]
I faced the same problem and sumanta solution solved it.

pklauzinski, I believe sumanta is right.
The only place that _checkNextHref is called is in _load function. 

`// Load the next set of content, if available
            _load = function() {`

testing with firebug, _load was not called at the beginning. only after jscroll triggered (with the wrong url since it has 'undefined'

Please take a look and fix it. It's a wonderful plugin.
Also the other issue #54 is not solved yet so if you can take a look at it too. It's about a situation where there is one/more jscroll on a page initially, and new jscroll is loaded dynamically with code from the server.

**Comment by alonziv** [comment]
I had the same issue.  Firefox was fine, but in Chrome the loading div would appear even if there was no "next" link.  sumanta-ghosh's solution resolved it.  Thanks for the great plugin!

**Comment by pklauzinski** [comment]
https://github.com/pklauzinski/jscroll/commit/2bd4b0a368da3d385ef1df5161b83d17e2a9177c

**Comment by sudhirbeldar** [comment]
@pklauzinski 

Could you please help me in calling ajax query on scroll event. Whenever user reached to bottom I need to fire an AJAX query to get data and display it. I cant find a solution on this
