### ISSUE TITLE
(in a userscript for reddit.com) It only appends page 2 when having login

### ISSUE THREAD

**Issue by darkred** [pklauzinski/jscroll#58]
I've made this userscript in order to use jScroll it in reddit.com and any subreddit

```javascript
// ==UserScript==
// @name        Reddit jScroll
// @namespace   
// @include     http://www.reddit.com/*
// @version     1
// @grant       none
// @require     https://raw.githubusercontent.com/pklauzinski/jscroll/master/jquery.jscroll.min.js
// ==/UserScript==

$('span.nextprev').jscroll({
  contentSelector: 'div.content'   
});
```
where `span.nextprev` is the selector for the _Next_ button
and `div.content` is the selector for the links content of every next page.

If open eg. reddit.com without login, then it works ok (it appends every next page).
The problem is when I try my userscript having login:
**it only appends page 2, not the next pages 
(it just shows _Loading..._ at the end of the appended page 2 )**
for example in:

1. http://www.reddit.com (I've only subscribed to 2 subreddits) 
2. eg. http://www.reddit.com/r/firefox/

Is my userscript wrong or it'is jScroll?

**Comment by pklauzinski** [comment]
@darkred - The element you call `$().jscroll` on should be the container into which the content will be loaded, not the selector for the next button. Your next button selector should be provided in the options as `nextSelector: 'span.nextprev a` - Additionally, the `nextSelector` needs to be an anchor `<a>` tag so that jScroll has an href to use for the next set of content.

Based on looking at your site's code, I think what you want is something like this:

```js
$('#siteTable').jscroll({
    nextSelector: 'span.nextprev a',
    contentSelector: '#siteTable'
});
```

I don't know what your ajax response looks like exactly, but if it is just like the original page content, then you will want your next page content to be filtered by what is within the `#siteTable` element, and not necessarily everything that is within `div.content`. Please let me know if this helps!

**Comment by pklauzinski** [comment]
@darkred - Also, make sure you are not linking to javascript from raw.github.com, as the headers will not be sent correctly and break the script in some browsers - see this post on stackoverflow: http://stackoverflow.com/questions/7180099/including-js-from-raw-github-com

Instead, I suggest you use something like https://rawgit.com/ or maintain the script on your server itself.

**Comment by darkred** [comment]
Thank you very much for the detailed and instructive replies!

I just tried your code and it only appends page 2.
Also, before it appends page 2, it adds the entries from the "recently viewed links" table
(please check the red arrows in my [screenshot](http://i.imgur.com/JDn1f8g.png) to see what I mean)

Unfortunately I still can't make the script work.
Please, login to reddit and help with this.

**Comment by pklauzinski** [comment]
@darkred  - Ok, I see the reason for both issues. As for the pagination, once you go to the section page, `span.nextprev` contains both "previous" and "next" links, but you only want jScroll to target the "next" link, so change your `nextSelector` to `span.nextprev a:last`.

Secondly, the "recently viewed links" table also uses the `thing` class, so you need a `contentSelector` that is more specific to the items within `#siteTable`. Try changing your code to this:

```js
$('#siteTable').jscroll({
    nextSelector: 'span.nextprev a:last',
    contentSelector: '#siteTable .thing'
});
```

**Comment by darkred** [comment]
I tried it and, yes, the "recently viewed links" section is no longer appended.
But unfortunately it only appends page 2, as well.

**Comment by pklauzinski** [comment]
Ah.. sorry, you also need to include `.nav-buttons` in your `contentSelector` so that it is loaded into the content to find the `nextHref`. Corrected code:

```js
$('#siteTable').jscroll({
    nextSelector: 'span.nextprev a:last',
    contentSelector: '#siteTable .thing, .nav-buttons'
});
```

I just tried this out on reddit.com and it works.

**Comment by darkred** [comment]
Now it works great!!
I've learnt a lot about your great plugin!
I now might be able to use it for other sites too.

Thanks a lot for all your help and for making this!

**Comment by pklauzinski** [comment]
@darkred - You may also want to add a `callback` option to hide or remove the `nav-buttons` div so that it does not disrupt the flow of content. For example:

```js
callback: function() {
    $('.nav-buttons').remove();
}
```

**Comment by darkred** [comment]
Thanks! Now it's perfect!
