### ISSUE TITLE
Scrolling table rows

### ISSUE THREAD

**Issue by markfqs** [pklauzinski/jscroll#64]
Hi,

I'm currently using jscroll as is the best and simplier approach (out-of-the-box) to achieve what I want. Although I'm facing some issues when using it to scroll table rows:

Given the jscroll binding:

```
$('.infinite-scroll').jscroll({
    debug: false,
    autoTrigger: true,
    nextSelector: 'a#NextScroll'
});
```

And the following HTML snippet:

```
<div>
    <table>
        <tbody>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Description</th>
        </tr>
        <tr>
            <td colspan="3">
                <span>
                    <a id="NextScroll" href="/visor/logpage"> NEXT </a>
                </span>
            </td>
        </tr>
    </tbody>
    </table>
</div>
```

I tried attaching the CSS selector class 'infinite-scroll' to both the outer div, the table, and the tbody tags. With all tests I got the same result as expected:

```
<div>
    <table>
        <tbody>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Description</th>
        </tr>
        <tr>
            <td colspan="3">
                <span>
                    <a id="NextScroll" href="/visor/logpage"> NEXT </a>
                </span>
            </td>
        </tr>
        <div class="jscroll-added">
            <tr>...</tr>
        </div>
    </tbody>
    </table>
</div>
```

The issue is as jscroll load the new content inside a new div 'jscroll-added'), the columns of the table are not aligned along all the page.

Is there any way to avoid o remove those 'jscroll-added' divs and simply add the AJAX loaded content as-is ?

**Comment by pklauzinski** [comment]
This is being addressed as an enhancement in #60.

**Comment by markfqs** [comment]
As per your info, in my case I solved my particular issue at jscroll v2.2.4 adding:

$('.jscroll-added').children().unwrap(); // Remove the added div

Just after removing the privous 'next' selector (line 165 of v2.2.4 jquery.jscroll).

I just opened an issue to github to see if there is a better way or enhancement planned

**Comment by GaryLProthero** [comment]
Just a note: this also works with ul/li's.  However, you will need to make sure your "next" link has an li as its parent or else only one page will load in.

**Comment by zoltan-sule** [comment]
my solution is maybe less elegant but working. It is a similar approach like wezzix's one in #60.

[How to scroll table rows with jQuery jScroll? - stackoverflow](https://stackoverflow.com/questions/58503672/how-to-scroll-table-rows-with-jquery-jscroll/58503673#58503673)
