### ISSUE TITLE
How do you integrate this with your ajax code?

### ISSUE THREAD

**Issue by UsingTheCode** [pklauzinski/jscroll#74]
$('.infinite-scroll').jscroll({
    loadingHtml: '<img src="loading.gif" alt="Loading" /> Loading...',
    padding: 20,
    nextSelector: 'a.jscroll-next:last',
    contentSelector: 'li'
});

Given this code, where would I stick my AJAX calls? That's the only part that confuses me.

**Comment by pklauzinski** [comment]
@UsingTheCode - the ajax call is made from the `href` attribute defined in your `nextSelector` option. In other words, `nextSelector` should be an anchor element within your `.infinite-scroll` element. jScroll will find that link, take the `href` value and call it as your next set of content, and for each subsequent set of content.
