### ISSUE TITLE
Doesn't stop loading

### ISSUE THREAD

**Issue by espenlg** [pklauzinski/jscroll#79]
Hi there,

I've tried to implement jScroll at http://dev.agderposten.no/cxense/va-lazy.php but the problem is it never stops loading. It's like I'm always at the bottom. I added autoTriggerUntil: 5 just to make it stop at some point.

Any idea what could cause this? I've tried in Safari, Chrome and Firefox and I also tried removing the CSS but didn't help.

**Comment by pklauzinski** [comment]
Does your content not fill the page? When `autoTrigger` is on, the next page loading is determined by the  bottom of the current set of content being above the bottom of the browser window. If that content is short, it will keep loading until it is below the bottom of the window. That is how it detects when to load the next set of content.

You may want to try adjusting the `padding` option to get the result you want.

**Comment by espenlg** [comment]
Thank you for the quick reply! I have tried to resize the window to make sure the first piece of content fills the entire screen and that didn't help. I have also tried various values of padding from 0 to 1000. The console says "jScroll: 0 from bottom. Loading next request..." .. 5 times in just a few secs.

**Comment by GonzaloCalandria** [comment]
I'm having the same problem! did you found a solution for this problem?

**Comment by espenlg** [comment]
I'm afraid not, so I found another solution http://imakewebthings.com/waypoints/shortcuts/infinite-scroll/ and that worked like a charm.

**Comment by pklauzinski** [comment]
Are you using flexbox in your layout?

**Comment by GonzaloCalandria** [comment]
I don’t know what’s flexbox is :)

**Comment by pklauzinski** [comment]
I have tentatively deduced that this issue occurs when `display: flex` (flexbox) is used for the layout grid of then content you are loading with jScroll.

I will have to test further, but that is the only commonality I have seen between two reports so far of this issue - including the link given above by @espenlg.

**Comment by Dill1** [comment]
I have this problem using jquery 2.1.3. When I temporarily change to jquery 1.4.0 the problem goes away. I haven't experimented with which version exactly it starts happening, but my guess is jquery 2.0. I set debug to true. When the problem is happening it is detecting that it is -1600 away from the bottom (for example, or some other big negative number), so setting padding to -20000 stops the loading, but that of course doesn't help anyone.

**Comment by GonzaloCalandria** [comment]
What i'm seeing in the debuging is that the values of `iTotalHeight` and `$inner.outerHeight()` are always the same values. I don't know too much what that means :/

**Comment by Dill1** [comment]
It is 1.7 vs 1.8. This may help indicate the problem:
http://stackoverflow.com/questions/26790396/jquery-1-8-and-higher-set-the-height-of-a-div-to-the-same-as-another-div

**Comment by GonzaloCalandria** [comment]
jscroll.com is down... it's because @pklauzinski is working on a fix?

**Comment by pklauzinski** [comment]
No, the host server was down due to a cPanel upgrade bug which has affected
a lot of people. It's back up now!

Thanks for the note on the jQuery versions. I will look into this.

**Comment by Dill1** [comment]
My pleasure. Thanks for looking into it, looking forward to hearing from you, I'm going live shortly and I would love to use jscroll with the latest JQuery.
jscroll is really nice to use, full featured and intuitive and pretty well documented, what a great plugin should be!

**Comment by GonzaloCalandria** [comment]
I just put a height in the scroll container and worked! 
Now i have a question... what if the jscroll is destroyed (because there aren't more `<a>` tags) and i load from ajax more content inside the scroll container? what do i need to do to make jscroll work again?
I'm calling again after the ajax call `$('.scroll').jscroll()` without luck.

**Comment by VictorUVE** [comment]
I had a section tag with { float: left; } containing the div associated with the jscroll. And it kept loading and loading. That section was the last element in the page.

When I removed the { float: left; } it started to work well again.
It was solved as well adding a clearer element (with { clear: both; }) on the bottom of the page.

So if some of you got the same problem, maybe this could help.

**Comment by Dill1** [comment]
GonzaloCalandria: maybe you need to append a new link to the div before running .jscroll again?

**Comment by gstricklind** [comment]
I'm also experiencing this bug: jScroll: -603 from bottom. Loading next request...

I've tried forcing a height for each article as well as enqueuing 1.4 jquery. I've inspected all elements within the content to scroll for any type of flex with nothing to be found. Also tried altering the floats and clears to no avail yet.

**Comment by abdul-khaliq** [comment]
Hi,
i have a list of 20 div
Now i want to use pagination without any .php call (without any ajax). i already fetch all data. i want to show 10 div from 20 and rest 10 will be show after page scroll...

Thanks for any help.

**Comment by iamakimmer** [comment]
also confirm the issue when using flexbox

**Comment by fradelg** [comment]
I am not using flex but I the issue is gone by ading the following rule to my CSS

```
.jscroll-inner {
  overflow: hidden;
}
```

I hope it can help someone else. It can be added to jscroll in the line 62 of jquery.jscroll.js

```
$e.contents().wrapAll('<div class="jscroll-inner" style="overflow: hidden" />');
```

**Comment by GonzaloCalandria** [comment]
Was this issue fixed?

**Comment by shizhua** [comment]
I am facing the same issue. And just fixed it as @fradelg mentioned adding following to my css.
`.jscroll-inner {
  overflow: hidden;
}`

**Comment by Saied1988** [comment]
I found a solution for this problem 
First you need to give a class name for the last page div
ex: `<div class="lastPage">Page content</div>`
Second go to the jqurey.scroll.js,then go to `_load = function()` before  `data.waiting = true;` and `$inner.append` add this code snippet 

`var htmldata ;`  
`//if last page exists or added then don't show loading image else show loading image` 
` if ($('.lastPage').length) {`          
`htmldata='';`
` }else{`
`htmldata = '<div class="jscroll-loading" id="jscroll-loading">' + _options.loadingHtml +    '</div>';`
`}`

After adding this code snippet you need to change `$inner.append` to this  <br/>               `$inner.append('<div class="jscroll-added" />')`
                    `.children('.jscroll-added').last()`
                   ` .html(htmldata)`
                    `.promise()`
                   ` .done(function(){`
                       ` if (_options.loadingFunction) {`
                            `_options.loadingFunction();`
                        `}`
                   ` });`

**Comment by arvindpdmn** [comment]
I tried applying the .jscroll-inner CSS fix mentioned earlier. I tried with minimal content (content less than window height) as well as large content (content exceeds window height). In both cases, jscroll infinitely keeps adding content at the end even though scroll is at the top of the window. 

My code is attached. (I had trouble embedding formatted code.) Code was placed in my web server root and loaded as `http://localhost/sc.htm`

[sample1.zip](https://github.com/pklauzinski/jscroll/files/347093/sample1.zip)

**Comment by arvindpdmn** [comment]
I think I found the solution. All I did was to add `<!DOCTYPE html>` at the start of my HTML file. This solves the problem!

**Comment by TangMonk** [comment]
`.jscroll-inner { overflow: hidden; }` works !

**Comment by mcardia** [comment]
@fradelg solution works!

**Comment by amanda-ariyaratne** [comment]
> I am not using flex but I the issue is gone by ading the following rule to my CSS
> 
> ```
> .jscroll-inner {
>   overflow: hidden;
> }
> ```
> I hope it can help someone else. It can be added to jscroll in the line 62 of jquery.jscroll.js
> 
> ```
> $e.contents().wrapAll('<div class="jscroll-inner" style="overflow: hidden" />');
> ```

thank you, it works!!
