### ISSUE TITLE
Hide Pagination Links

### ISSUE THREAD

**Issue by tmblog** [pklauzinski/jscroll#87]
Hi great plugin thanks.
I am using 
`$( ".pagination" ).css( "display", "none" );`

to hide pagination link, but it reappears on the next response, anyway to hide pagination links?

**Comment by pklauzinski** [comment]
@tmblog - yes, use the `pagingSelector` option to hide pagination. For example:

```
$('.jscroll').jscroll({
    pagingSelector: '.pagination'
});

**Comment by tmblog** [comment]
Ah yes, thank you. Missed that from the docs! My bad.
