### ISSUE TITLE
Loading all the views Irrespective of scrolling

### ISSUE THREAD

**Issue by naresh86** [pklauzinski/jscroll#90]
Hi,

I have developed Sample application to load the partial views while scrolling,but my problem was its loading all the views when page loads.
this is my view code
<div id="container" >
    <div class="scroll" >
        @foreach (var item in Model)
{

        <a href="@Url.Action(@item.ViewName,"Home")"></a>
        <br />

            

}
    </div>
</div>
<script src="Scripts/jquery-1.11.0.min.js"></script>

<script src="Scripts/jquery-ui-1.8.24.min.js"></script>
<script src="Scripts/jquery.jscroll.js"></script>

<script type="text/javascript">

    $(function () {
        alert(1);
        $('.scroll').jscroll({
            debug: true,

            loadingHtml: '<img src="Images/loading_spinner.gif" alt="Loading" /> Loading...',
            autoTrigger: true
        });
    });
</script>

Can you help me out....?

**Comment by pklauzinski** [comment]
Not sure, but it sounds like all of your views must be within the viewport when the page loads and that's why they are being triggered. Do you have an example link to it?

**Comment by pklauzinski** [comment]
Closing due to lack of followup.
