### ISSUE TITLE
Is it possible to use a jQuery selector for nextSelector?

### ISSUE THREAD

**Issue by darkred** [pklauzinski/jscroll#93]
I'm trying to make a userscript for majorgeeks.com.
My userscript doesn't work (it doesn't append page 2).

As you had described me in [here](https://github.com/pklauzinski/jscroll/issues/75#issuecomment-139036352)
> Also, make sure that your nextSelector is just the selector text, and not a jQuery object itself. 

So, my code is:
```
$('div.geekycontent').last().jscroll({
    nextSelector: $('.pagelink').last().prev().find('a'),
    contentSelector: 'div.geekycontent, .pagelink',
});

```

I believe the problem in my code lies int the `nextSelector`:
the selector for `nextSelector` that I'm after is the one-before-the-last `.pagelink` in the page.
I ended up using jQuery: ` $('.pagelink').last().prev().find('a'),` because I couldn't select it via CSS (and I think it's not possible without using jQuery).

How can I change it to make it work? (is it possible?)

----

_For reference, running `$('.pagelink').last().prev().find('a')` in Browser Console results in:_
```
Object { 0: <a>, length: 1, prevObject: Object, context: HTMLDocument → www.majorgeeks.com }
```

**Comment by guanzo** [comment]
You can translate that jquery statement into a selector with `:nth-last-child(n)`. `.pagelink:nth-last-child(2) a`

**Comment by darkred** [comment]
Thanks for the reply. Unfortunately the script still doesn't paginate next page:
```
$('div.geekycontent').last().jscroll({
    nextSelector: '.pagelink:nth-last-child(2) a',
    contentSelector: 'div.geekycontent, .pagelink',
});
```
And, opening Firefox Inspector, and doing a search with your selector, 
it doesn't select the 'Next page' icon, i.e. the `>`.

**Comment by darkred** [comment]
I had used a wrong selector. Using `$('content')` and adding a few more selectors in ContentSelector
it appends page 2, therefore my question is answered: it is possible to a jQuery selector for nextSelector:

```
// ==UserScript==
// @name        MajorGeeks - Infinite Scrolling
// @include     http://www.majorgeeks.com/*
// @grant       none
// @require     http://code.jquery.com/jquery-2.1.4.min.js
// @require     https://cdn.rawgit.com/pklauzinski/jscroll/master/jquery.jscroll.js
// ==/UserScript==

$('#content').jscroll({
    nextSelector: $('.pagelink').last().prev().find('a'),
    contentSelector: '.geekydate, .geekycontent, .pagelink, .pagelinkselected, ',
});
```

The only problem now is that it doesn't append pages 3, 4 and on.
Why is that?

**Comment by darkred** [comment]
Thanks a lot, @guanzo.
 Here it is fixed:

```
$('.pageborder').last().jscroll({
	nextSelector: '#content .pagelink:nth-last-child(6) a',
	contentSelector: '#content',
});
```
