### ISSUE TITLE
reinitialize jScroll 

### ISSUE THREAD

**Issue by SaraiMoreno** [pklauzinski/jscroll#98]
I have a news section with links to products, in this I am implementing the jscroll but when I go to a detail of any product to return to my news section the jscroll no longer works , I think that was destroyed when not find a href , I would like to know how to restart again jscroll

**Comment by pklauzinski** [comment]
If it does not find the `nextHref` selector then it will self-destroy. Are you defining an appropriate `nextSelector`? Also, you can use the `callback` option to reinitialize with new options if you need to.
